# Generated by Django 5.1.4 on 2024-12-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_first_name', models.CharField(max_length=30)),
                ('user_last_name', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('weight', models.DecimalField(decimal_places=1, max_digits=4)),
                ('weight_target', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
        ),
    ]
