# Generated by Django 5.1.4 on 2024-12-31 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_user_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('height', models.FloatField(help_text='Height in cm')),
                ('weight', models.FloatField(help_text='Weight in kg')),
                ('activity', models.CharField(choices=[('sedentary', 'Sedentary'), ('light', 'Lightly Active'), ('moderate', 'Moderately Active'), ('active', 'Active'), ('very_active', 'Very Active')], max_length=20)),
                ('goal', models.CharField(choices=[('weight_loss', 'Weight Loss'), ('maintenance', 'Maintenance'), ('weight_gain', 'Weight Gain')], max_length=20)),
                ('daily_calories', models.PositiveIntegerField()),
                ('daily_carbohydrates', models.PositiveIntegerField(help_text='Daily Carbohydrates in grams')),
                ('daily_proteins', models.PositiveIntegerField(help_text='Daily Proteins in grams')),
                ('daily_fats', models.PositiveIntegerField(help_text='Daily Fats in grams')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
