# Generated by Django 5.1.4 on 2025-01-03 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_userprofile_delete_user'),
        ('nutrition', '0003_alter_food_unit_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('weight', models.DecimalField(decimal_places=1, max_digits=4)),
                ('weight_target', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
