# Generated by Django 5.1.4 on 2024-12-24 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout_Unit',
            fields=[
                ('workout_unit_id', models.IntegerField(primary_key=True, serialize=False)),
                ('workout_unit_name', models.CharField(max_length=30)),
                ('workout_type', models.CharField(max_length=30)),
                ('calories_per_kg_per_h', models.DecimalField(decimal_places=15, max_digits=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
