# Generated by Django 5.1.4 on 2025-01-02 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout_Class',
            fields=[
                ('workout_class_id', models.IntegerField(primary_key=True, serialize=False)),
                ('workout_class', models.CharField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='Workout_Type',
            fields=[
                ('workout_type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('workout_type', models.CharField(max_length=255)),
                ('calories_per_kg_per_h', models.DecimalField(decimal_places=15, max_digits=16)),
                ('workout_class', models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='fitness.workout_class')),
            ],
        ),
    ]
