# Generated by Django 5.1.4 on 2025-01-02 19:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout_Unit',
            fields=[
                ('workout_type_unit', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('workout_length', models.IntegerField(default=0)),
                ('weight', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('calories_burned', models.IntegerField(default=0)),
                ('workout_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.workout_type')),
            ],
        ),
    ]
