# Generated by Django 5.1.4 on 2025-01-03 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_workout_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout_unit',
            name='workout_class',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='fitness.workout_class'),
            preserve_default=False,
        ),
    ]
