# Generated by Django 5.1.4 on 2025-01-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0003_workout_unit_workout_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout_class',
            name='workout_class',
            field=models.CharField(max_length=63, verbose_name='Übungsart'),
        ),
    ]
