# Generated by Django 5.1.4 on 2024-12-23 22:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food_Unit',
            fields=[
                ('food_unit_id', models.AutoField(primary_key=True, serialize=False)),
                ('food_unit_name', models.CharField(max_length=30, null=True)),
                ('time_eaten', models.DateTimeField(default=django.utils.timezone.now)),
                ('calories', models.IntegerField(default=0)),
                ('carbohydrates', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('fat', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('protein', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
