# Generated by Django 5.1.4 on 2024-12-31 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_userprofile_delete_user'),
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_unit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.userprofile'),
        ),
    ]
