# Generated by Django 5.1.4 on 2025-01-03 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_alter_food_unit_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_unit',
            name='food_categorie',
            field=models.CharField(choices=[('breakfast', 'Frühstück'), ('lunch', 'Mittagessen'), ('dinner', 'Abendessen'), ('snack', 'Snack')], default='Frühstück', max_length=10),
        ),
    ]
