# Generated by Django 5.1.4 on 2025-01-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0004_food_unit_food_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_unit',
            name='food_amount',
            field=models.IntegerField(default=100),
        ),
    ]
