# Generated by Django 5.1.4 on 2025-01-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0005_food_unit_food_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_unit',
            name='calories_per_100g',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='food_unit',
            name='carbohydrates_per_100g',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='food_unit',
            name='fat_per_100g',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='food_unit',
            name='protein_per_100g',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
    ]
