# Generated by Django 5.1.4 on 2025-01-04 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0006_food_unit_calories_per_100g_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_unit',
            name='food_categorie',
            field=models.CharField(choices=[('breakfast', 'Frühstück'), ('lunch', 'Mittagessen'), ('dinner', 'Abendessen'), ('snack', 'Snack')], default='Frühstück', max_length=20),
        ),
    ]
