# Generated by Django 5.1.4 on 2024-12-21 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_first_name', models.CharField(max_length=30)),
                ('user_last_name', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('weight', models.DecimalField(decimal_places=1, max_digits=4)),
                ('weight_target', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Workout_Type',
            fields=[
                ('workout_type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('workout_name', models.CharField(max_length=80)),
                ('workout_category', models.CharField(max_length=30)),
                ('calories_per_kg_per_h', models.DecimalField(decimal_places=15, max_digits=16)),
            ],
        ),
        migrations.CreateModel(
            name='Food_Unit',
            fields=[
                ('food_unit_id', models.IntegerField(primary_key=True, serialize=False)),
                ('fat', models.DecimalField(decimal_places=4, max_digits=8)),
                ('carbohydrates', models.DecimalField(decimal_places=4, max_digits=8)),
                ('protein', models.DecimalField(decimal_places=4, max_digits=8)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trackerapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Daily_Workouts',
            fields=[
                ('daily_workout_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trackerapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Daily_Food',
            fields=[
                ('daily_food_id', models.IntegerField(primary_key=True, serialize=False)),
                ('fat', models.DecimalField(decimal_places=4, max_digits=8)),
                ('carbohydrates', models.DecimalField(decimal_places=4, max_digits=8)),
                ('protein', models.DecimalField(decimal_places=4, max_digits=8)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trackerapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Workout_Unit',
            fields=[
                ('workout_unit_id', models.IntegerField(primary_key=True, serialize=False)),
                ('calories_per_kg_per_h', models.DecimalField(decimal_places=15, max_digits=16)),
                ('weight', models.DecimalField(decimal_places=1, max_digits=4)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trackerapp.user')),
            ],
        ),
    ]
