# Generated by Django 5.1.4 on 2024-12-22 16:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_unit',
            name='calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='food_unit',
            name='food_unit_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='food_unit',
            name='time_eaten',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='food_unit',
            name='carbohydrates',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='food_unit',
            name='fat',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='food_unit',
            name='food_unit_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='food_unit',
            name='protein',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
    ]
