# Generated by Django 5.1.4 on 2024-12-22 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0002_food_unit_calories_food_unit_food_unit_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daily_food',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='food_unit',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trackerapp.user'),
        ),
    ]
