# Generated by Django 5.1.4 on 2024-12-22 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0003_rename_user_id_daily_food_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_food',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trackerapp.user'),
        ),
    ]
