# Generated by Django 5.1.4 on 2024-12-24 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0005_rename_user_id_food_unit_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Food_Unit',
        ),
    ]
