# Generated by Django 5.1.3 on 2024-12-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0008_user_daily_user_food_user_workout'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('height', models.FloatField(help_text='Height in cm')),
                ('weight', models.FloatField(help_text='Weight in kg')),
                ('activity', models.CharField(choices=[('sedentary', 'Sedentary'), ('light', 'Lightly Active'), ('moderate', 'Moderately Active'), ('active', 'Active'), ('very_active', 'Very Active')], max_length=20)),
                ('goal', models.CharField(choices=[('weight_loss', 'Weight Loss'), ('maintenance', 'Maintenance'), ('weight_gain', 'Weight Gain')], max_length=20)),
                ('daily_calories', models.PositiveIntegerField()),
                ('daily_carbohydrates', models.PositiveIntegerField(help_text='Daily Carbohydrates in grams')),
                ('daily_proteins', models.PositiveIntegerField(help_text='Daily Proteins in grams')),
                ('daily_fats', models.PositiveIntegerField(help_text='Daily Fats in grams')),
            ],
        ),
    ]
