# Generated by Django 5.1.3 on 2025-01-03 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0010_alter_userprofile_gender'),
        ('trackerapp', '0010_remove_userprofile_username_userprofile_user_and_more'),
    ]

    operations = [
    ]
