# Generated by Django 5.1.4 on 2025-01-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0011_merge_20250103_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='activity',
            field=models.CharField(choices=[('sedentary', 'Sedentary'), ('light', 'Lightly Active'), ('moderate', 'Moderately Active'), ('active', 'Active'), ('very_active', 'Very Active')], default='sedentary', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='daily_calories',
            field=models.PositiveIntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='daily_carbohydrates',
            field=models.PositiveIntegerField(default=250, help_text='Daily Carbohydrates in grams'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='daily_fats',
            field=models.PositiveIntegerField(default=70, help_text='Daily Fats in grams'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='daily_proteins',
            field=models.PositiveIntegerField(default=75, help_text='Daily Proteins in grams'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='goal',
            field=models.CharField(choices=[('weight_loss', 'Weight Loss'), ('maintenance', 'Maintenance'), ('weight_gain', 'Weight Gain')], default='maintenance', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='height',
            field=models.FloatField(default=170.0, help_text='Height in cm'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weight',
            field=models.FloatField(default=70.0, help_text='Weight in kg'),
        ),
    ]
