# Generated by Django 5.1.3 on 2025-01-03 22:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0012_alter_userprofile_activity_alter_userprofile_age_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=django.utils.timezone.now)),
                ('calories_eaten', models.PositiveIntegerField(default=0)),
                ('calories_burned', models.PositiveIntegerField(default=0)),
                ('daily_calorie_target', models.PositiveIntegerField(default=2000)),
                ('calorie_result', models.IntegerField(default=0)),
                ('eaten_fat', models.FloatField(default=0.0)),
                ('eaten_carbohydrates', models.FloatField(default=0.0)),
                ('eaten_protein', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Daily_Food',
        ),
    ]
