# Generated by Django 5.1.3 on 2025-01-03 23:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0013_dailyfood_delete_daily_food'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyfood',
            unique_together={('user', 'day')},
        ),
    ]
