# Generated by Django 5.1.3 on 2025-01-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0014_alter_dailyfood_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyfood',
            old_name='eaten_carbohydrates',
            new_name='carbohydrates',
        ),
        migrations.RenameField(
            model_name='dailyfood',
            old_name='eaten_fat',
            new_name='carbohydrates_eaten',
        ),
        migrations.RenameField(
            model_name='dailyfood',
            old_name='eaten_protein',
            new_name='fat',
        ),
        migrations.AddField(
            model_name='dailyfood',
            name='fat_eaten',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dailyfood',
            name='protein',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dailyfood',
            name='protein_eaten',
            field=models.FloatField(default=0.0),
        ),
    ]
