# Generated by Django 5.1.4 on 2025-01-04 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0011_merge_20250103_2103'),
        ('trackerapp', '0015_rename_eaten_carbohydrates_dailyfood_carbohydrates_and_more'),
    ]

    operations = [
    ]
