# Generated by Django 5.1.4 on 2025-01-04 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0016_merge_20250104_1126'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_Food',
            fields=[
                ('daily_food_id', models.IntegerField(primary_key=True, serialize=False)),
                ('fat', models.DecimalField(decimal_places=4, max_digits=8)),
                ('carbohydrates', models.DecimalField(decimal_places=4, max_digits=8)),
                ('protein', models.DecimalField(decimal_places=4, max_digits=8)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='DailyFood',
        ),
    ]
