# Generated by Django 5.1.4 on 2025-01-04 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0011_merge_20250103_1515'),
        ('trackerapp', '0017_daily_food_delete_dailyfood'),
    ]

    operations = [
    ]
