# Generated by Django 5.1.4 on 2025-01-04 14:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0018_merge_20250104_1549'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=django.utils.timezone.now)),
                ('calories_eaten', models.PositiveIntegerField(default=0)),
                ('fat_eaten', models.FloatField(default=0)),
                ('carbohydrates_eaten', models.FloatField(default=0)),
                ('protein_eaten', models.FloatField(default=0)),
                ('calories_burned', models.PositiveIntegerField(default=0)),
                ('daily_calorie_target', models.PositiveIntegerField(default=2000)),
                ('calorie_result', models.IntegerField(default=0)),
                ('fat', models.FloatField(default=0)),
                ('carbohydrates', models.FloatField(default=0)),
                ('protein', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'day')},
            },
        ),
        migrations.DeleteModel(
            name='Daily_Food',
        ),
    ]
