# Generated by Django 5.1.4 on 2025-01-05 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0020_dailywaterintake'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_food',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user_workout',
            name='user',
        ),
        migrations.DeleteModel(
            name='User_Daily',
        ),
        migrations.DeleteModel(
            name='User_Food',
        ),
        migrations.DeleteModel(
            name='User_Workout',
        ),
    ]
