# Generated by Django 5.1.3 on 2025-01-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0021_remove_user_food_user_remove_user_workout_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyfood',
            name='carbohydrates',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyfood',
            name='carbohydrates_eaten',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyfood',
            name='fat',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyfood',
            name='fat_eaten',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyfood',
            name='protein',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyfood',
            name='protein_eaten',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
