# Generated by Django 5.1.4 on 2025-01-05 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0022_dailyfood_intermittent_timer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyfood',
            name='intermittent_timer',
        ),
    ]
