# Generated by Django 5.1.4 on 2025-01-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0023_remove_dailyfood_intermittent_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='intermittent_timer',
            field=models.DateTimeField(null=True),
        ),
    ]
