# Generated by Django 5.1.4 on 2025-01-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0024_userprofile_intermittent_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='intermittent_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='intermittent_timer',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
