# Generated by Django 5.1.4 on 2025-01-05 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapp', '0022_alter_dailyfood_carbohydrates_and_more'),
        ('trackerapp', '0025_userprofile_intermittent_type_and_more'),
    ]

    operations = [
    ]
